version: 2.1
description: Publish React Native apps to Expo

orbs:
  expo_example:
    jobs:
      expo_job:
        parameters: 
          release_channel: 
            description: which release channel
            type: string
            default: dev
        steps:
          - build_command
          - expo_command
    commands:
      build_command:
        steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match
              - v1-dependencies-
          - run: npm install
          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
      expo_command:
        steps:
          - run:
              name: Login into Expo
              command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          - run:
              name: Publish to Expo
              command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel <<parameters.release_channel>>
    executors:
      docker:
        - image: circleci/node:13.10.1

workflows:
  publish_to_expo:
    jobs:
      - expo_example/expo_job:
          name: expo_dev
          release_channel: dev
          filters:
            branches:
              only: development
      - expo_example/expo_job:
          name: expo_prod
          release_channel: default
          filters:
            branches:
              only: master
